yatube/about/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

app_name = 'about'

urlpatterns = [
    path('author/',
         TemplateView.as_view(
             template_name='about/author.html'
         ), name='author'),
    path('tech/',
         TemplateView.as_view(
             template_name='about/tech.html'
         ), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='postsname'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('like/', views.likes_post, name='post_like')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации',
                                    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts",
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="posts"
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    liked = models.ManyToManyField(User,
                                   default=None,
                                   blank=True,
                                   related_name='liked')

    def __str__(self):
        return self.text

    group = models.ForeignKey(
        Group,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, относительно поста',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'записи', 'Авторы', 'посты'


LIKE_CHOICES = (
        ('Like', 'Like'),
        ('Unlike', 'Unlike'),
    )


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        blank=True,
        null=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(verbose_name='Текст комментария',
                            help_text='Введите текст комментария')
    created = models.DateTimeField('Дата публикации', auto_now_add=True)

    class Meta:
        ordering = ('created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )


class Likes(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='user_like')
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='post_like'
                             )
    value = models.CharField(choices=LIKE_CHOICES,
                             default='Like',
                             max_length=10)

    def __str__(self):
        return str(self.post)

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'text',
            'group',
            'image',
        )
        labels = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
            'image': 'Загружаемая картинка',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User, Follow, Likes
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from .units import paginator_posts, MESSAGE_N
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.all()
    user = request.user
    context = {
        'page_obj': paginator_posts(post_list, MESSAGE_N, request),
        'user': user
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    post_list = Post.objects.all()
    context = {
        'group': group,
        'page_obj': paginator_posts(post_list, MESSAGE_N, request)
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    user_post_list = author.posts.select_related('author')
    following = (request.user.is_authenticated and (Follow.objects.filter(
        user=request.user, author=author).exists()))
    context = {
        'page_obj': paginator_posts(user_post_list, MESSAGE_N, request),
        'author': author,
        'following': following,

    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id, ):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()

        return redirect('posts:profile', post.author)

    return render(
        request,
        'posts/create_post.html',
        {
            'form': form,
        }
    )


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    context = {
        'page_obj': paginator_posts(posts, MESSAGE_N, request)
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author and Follow.objects.filter(
            user=request.user, author=author).exists():
        Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', author)


@login_required
def likes_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)

        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)
        like, create = Likes.objects.get_or_create(user=user, post_id=post_id)

        if not create:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        like.save()
    return redirect('posts:index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Добавить запись
            {% endif %}
          </div>
          {% include 'includes/errors.html' %}
          {% if is_edit %}
          <form method="post" enctype="multipart/form-data"
          action="{% url 'posts:post_edit' form.instance.pk %}">
        {% else %}
          <form method="post" enctype="multipart/form-data"
          action="{% url 'posts:post_create' %}">
        {% endif %}
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              {% include 'includes/forms.html' %}
              <small id="id_group-help" class="form-text text-muted">
              </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Избранные авторы
{% endblock %}
{% load thumbnail %}
{% block content %}
    <article>
      {% include 'includes/switcher.html' %}
      {% if post_count == 0 %}
    <p>Подписок нет</p>
    {% else %}
      {% for post in page_obj %}
        <ul>
          <li>
            Автор:
            {% if post.author.get_full_name %}
              <a href="{% url 'posts:profile' post.author.username %}">
                {{ post.author.get_full_name }}
              </a>
            {% else %}
              <a href="{% url 'posts:profile' post.author.username %}">
                {{ post.author.username }}
              </a>
            {% endif %}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <li>
            Группа: {{ post.group|default:"Нет" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}" alt="">
        {% endthumbnail %}
        <p>
          {{ post.text|truncatewords:50 }}
        </p>
        {% if post.group %}
          <a href="{% url 'posts:postsname' post.group.slug %}">
            Все записи группы </a>
        {% endif %}
        <p>
          <a href="{% url 'posts:post_detail' post.pk %}">Читать полностью </a>
        </p>
        </article>
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
    {% endif %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
  <p>{{ post.text }}</p>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
    <div class="container py-5">
    {% include 'includes/switcher.html' %}
{% for post in page_obj %}
    <div class="card-header d-flex justify-content-between">
  <ul>
    <li>
        Автор: <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
    </div>
  <p>{{ post.text }}</p>
    {% if post.image %}
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    {% endif %}
  <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-outline-dark">подробная информация</a>
  {% if post.group %}
    <p><a href="{% url 'posts:postsname' post.group.slug %}" class="btn btn-outline-dark">все записи группы</a></p>
  {% endif %}
    {% include 'includes/likes.html' %}

  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост {{ post }}|truncatechars:30  }}{% endblock %}

{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <!-- если у поста есть группа -->
            <li class="list-group-item">
              Группа: {{ group }}
              <p><a href="{% url 'posts:postsname' post.group.slug %}">все записи группы</a></p>
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
        {% if post.image %}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          {% endif %}
          <p style="word-wrap: break-word">
           {{ post.text }}
          </p>
        {% include 'includes/comments.html' %}
          <p>
            {% if post.author == user %}
              <a href="{% url 'posts:post_edit' post.id %}">Редактировать пост</a>
            {% endif %}
          </p>
        </article>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}

{% block content %}
      <div class="mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }}</h3>
        <h3>Всего подписок: {{ user.follower.count }}</h3>
        <h3>Всего подписчиков: {{ author.following.count }}</h3>
      {% if request.user.username != author.username %}
      {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %} " role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
      {% endif %}
            {% for post in page_obj %}
                <article>
                  <ul>
                    <li>
                      Автор: {{ author.get_full_name }}
                      <a href="{% url 'posts:profile' author.username %}">все посты пользователя</a>
                    </li>
                    <li>
                      Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                  </ul>
                  <p>
                    {{ post.text }}
                      {% if post.image %}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          {% endif %}
                  </p>
                  <a href="{% url 'posts:post_detail' post.pk %}" class="btn btn-outline-dark">Подробная информация </a>
                </article>
                {% if post.group %}
                <a href="{% url 'posts:postsname' post.group.slug %}" class="btn btn-outline-dark">Все записи группы</a>
                {% endif %}
                {% if not forloop.last %}<hr>{% endif %}
            {% endfor%}
        {% if not forloop.last %}<hr>{% endif %}
        <!-- Остальные посты. после последнего нет черты -->
        <!-- Здесь подключён паджинатор -->
      {% include 'includes/paginator.html' %}
      </div>
{% endblock %}